# Generated by Django 3.2.3 on 2021-05-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('scorecard', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scorecard.scorecard')),
            ],
        ),
    ]
