# Generated by Django 3.2.3 on 2021-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
